apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-mysql
spec:
  storageClassName: retained-ebs-sc
  volumeName: metadata-mysql-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
