apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata-db
spec:
  storageClassName: retained-ebs-sc
  volumeName: metadata-db-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
