apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
spec:
  claimRef:
    kind: PersistentVolumeClaim
    namespace: kubeflow
    name: $(minioPvcName)
  persistentVolumeReclaimPolicy: Retain
  storageClassName: retained-ebs-sc
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: $(minioPersistentVolumeHandle)
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.ebs.csi.aws.com/zone
          operator: In
          values:
          - eu-central-1a


    
