apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  maintainer: kineo.ai
namespace: kubeflow
generatorOptions:
  # name suffix hash is not propagated correctly to base resources
  disableNameSuffixHash: true
configMapGenerator:
- name: kineo-metadata-db-parameters
  env: params.env
bases:
- ../db
resources:
- metadata-db-pv.yaml
patchesStrategicMerge:
- metadata-db-pvc-patch.yaml
vars:
- name: metadataMysqlPersistentVolumeHandle
  objref:
    kind: ConfigMap
    name: kineo-metadata-db-parameters
    version: v1
  fieldref:
    fieldpath: data.metadataMysqlPersistentVolumeHandle
configurations:
- params.yaml