varReference:
- path: spec/template/spec/volumes/persistentVolumeClaim/claimName
  kind: Deployment
- path: metadata/name
  kind: PersistentVolumeClaim
- path: spec/volumeName
  kind: PersistentVolumeClaim
- path: metadata/name
  kind: PersistentVolume
- path: spec/claimRef/name
  kind: PersistentVolume